FROM golang:1.17-alpine as builder

WORKDIR /golang

COPY . .

RUN go env -w GO111MODULE=off && go build -o ./bin/output ./src/main.go

FROM scratch

COPY --from=builder /golang/bin /

CMD ["/output"]
